## day objectives:
#### functional programming
##### list compression
#### iterators and generators
#### map
#### filter
##### lambda

# list comprehension

In [1]:
# list comprehension is very easy way to create list 
## compared with for loop
# program using list comprehension
n=10
li=[]
for i in range(1,n+1):
    li.append(i)
print(li)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [5]:
## using list comprehension
li=[i for i in range(1,11)]
li

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [6]:
## cubes
li=[i**3 for i in li]
li

[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

In [7]:
k=[10,20,5,2]
li=[i**2 for i in li]
li

[1, 64, 729, 4096, 15625, 46656, 117649, 262144, 531441, 1000000]

In [8]:
## list comprehension to check leapyear
st=1970
et=2020
leapyear=[i for i in range(st,et+1)
          if(i%400==0) or (i%100!=0 and i%4==0)]
leapyear

[1972, 1976, 1980, 1984, 1988, 1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020]

In [9]:
st=1940
et=2010
leapyear=[i for i in range(st,et+1)
          if(i%400==0) or (i%100!=0 and i%4==0)]
leapyear

[1940,
 1944,
 1948,
 1952,
 1956,
 1960,
 1964,
 1968,
 1972,
 1976,
 1980,
 1984,
 1988,
 1992,
 1996,
 2000,
 2004,
 2008]

In [13]:
def cumulative(n):
    sum=0
    li=[]
    for i in range(1,n+1):
        sum=sum+i
        print(sum)
        li.append(sum)
    print(li)
cumulative(4)
    

1
3
6
10
[1, 3, 6, 10]


In [14]:
def cumulative(n):
    multiplication=1
    li=[]
    for i in range(1,n+1):
        multiplication=multiplication*i
        print(multiplication)
        li.append(multiplication)
    print(li)
cumulative(4)
 

1
2
6
24
[1, 2, 6, 24]


In [21]:
n=6
cumulativesum=[sum(range(1,i+1)) for i in range(1,n+1)]
cumulativesum

[1, 3, 6, 10, 15, 21]

In [24]:
n=6
cumulativemultiplication=[multiplication(range(1,i+1)) for i in range(1,n*1)]
cumulativemultiplication

NameError: name 'multiplication' is not defined

In [25]:
## iterators
## iterator is an object that contains number of elements
## 2-methods
# iter()
# next()
# all ds are all iterable objects


In [26]:
it='python'
it=iter('python')
print(it)


In [27]:
print(next(it))

p


In [28]:
print(next(it))

y


In [29]:
it='python'
for i in it:
    print(i)

p
y
t
h
o
n


In [30]:
a='pythonprogram'
a=iter('pythonprogram')
print(a)

In [31]:
print(next(a))

p


In [32]:
a='pythonprogram'
for i in a:
    print(i)

p
y
t
h
o
n
p
r
o
g
r
a
m


In [35]:
course = ['c','c++','Python']
result = iter(course)
print(next(result))
print(next(result))
print(next(result))

c
c++
Python


In [36]:
Btech=['it','cse','ece','mech']
result = iter(Btech)
print(next(result))
print(next(result))
print(next(result))
print(next(result))

it
cse
ece
mech


In [37]:
## generators
# generator is a function we can create iterators using generators
# in other words generator is a function which returns iterable objects
#it uses "yield" instead of return

    

In [40]:
def generatorfunction():
    yield "jaan"
    yield "jaanu"
    yield "janvi"
generatorfunction()
for value in  generatorfunction():
    print(value)
  

jaan
jaanu
janvi


In [42]:
## square of a numbers upto given range
def gen():
    n=2
    while True:
        n**=2
        yield n
a=gen()
for i in range(5):
    print(next(a))

4
16
256
65536
4294967296


In [43]:
def gen():
    n=3
    while True:
        n**=3
        yield n
a=gen()
for i in range(5):
    print(next(a))

27
19683
7625597484987
443426488243037769948249630619149892803
87189642485960958202911070585860771696964072404731750085525219437990967093723439943475549906831683116791055225665627


# Maps in Python

It produces a list of results that it apply given function to each item of a given iterable(lists,tuple,sets etc)
syntax: map(function,iterable)
    

In [46]:
def addition(n):
    return n+n
result=list(map(addition,range(1,5)))
print(result)
     

[2, 4, 6, 8]


In [48]:
def multiplication(k):
    return k*2
result=list(map(multiplication,range(1,10)))
print(result)

[2, 4, 6, 8, 10, 12, 14, 16, 18]


In [49]:
def squareofnumb(n):
    return n*n
result=set(map(squareofnumb,range(1,5)))
print(result)

{16, 1, 4, 9}


In [50]:
def squareofnumb(n):
    return n*n
result=tuple(map(squareofnumb,range(1,5)))
print(result)

(1, 4, 9, 16)


# Filters in Python 

used to check whether the given element is boolean or not
- this method filters the given iterable,test each element is true or false and returns the element which is true

# syntax
- f:x->{T<F}

In [57]:
li=[1,2,'a','b','c',3]
def isdigit(c):
    c=str(c)
    if c.isdigit():
        return True
    return False
isdigit('a')
list(filter(isdigit,li))
    

[1, 2, 3]

# Numpy

- Numpy is a python library and a fundamental package for scientific computing in python
- It is used to create multidimensional arrays for fast operations
- Use the following import conversion to access numpy library
- import numpy as np
- Numpy have a fixed size of arrays used to store a collection of elements,unlike python lists
- there are 3 types of arrays called 1D,2D,3D arrays

In [58]:
# creating 1D array using numpy
import numpy as np
array_1D=np.array([2,4,5,6,7,9])
print(array_1D)

[2 4 5 6 7 9]


In [1]:
import numpy as np
array_2D=np.array([[2,4,5,6,7,9],[6,8,4,6,7]])
print(array_2D)

[list([2, 4, 5, 6, 7, 9]) list([6, 8, 4, 6, 7])]


In [4]:
import numpy as np
array_2D=np.array([[2,4,5,6,7,9],[6,8,4,6,7]])
print(array_2D)

[list([2, 4, 5, 6, 7, 9]) list([6, 8, 4, 6, 7])]


In [6]:
import numpy as np
li=[1,2,3,'z']
a=np.array(li)
a

array(['1', '2', '3', 'z'], dtype='<U11')

- If the size of the arary is large to type,we can use array range called "arrange"

In [8]:
# example
# To print 1D array between 1 to 15
import numpy as np
a=np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


- Creating array using arange and reshape function function.If the array size is too large,then Numpy will kips the middle numbers for given range.for example print 1000 numbers in a 1D array.

In [9]:
import numpy as np
a2=np.arange(10000)
a2

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [15]:
a2=np.arange(10000).reshape(100,100)
print(a2)

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [20]:
a2=np.arange(100).reshape(2,50)
a2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [21]:
a2=np.arange(50).reshape(10,5)
a2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [32]:
import numpy as np
x = np.zeros((3,2))
print(x)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [33]:
import numpy as np
x = np.ones((3,2))
print(x)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [34]:
# diagonal
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [35]:
f=np.array([1,2,3])
f

array([1, 2, 3])

In [36]:
# horizontal(rows) 3 lines filled with f[list],vertically 1 line column
np.tile(f,(3,1))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [37]:
# i want 2 to 50 random value
50*np.random.random()+2

23.934863956914942

# Pandas

- pandas basically use for data analysis.it is build on top of numpy only
- we will mostly be using this pandas package a lot
- in fact if you are going to use it heavily for any data manipulation,any sort of data analysis and any sort of datavisualization and any sort of machine learning model building ##### datavisualisation

# create pandas series

In [40]:
import pandas as pd
a=pd.Series([1,2,3,4,5])
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [41]:
type(a)

pandas.core.series.Series

In [42]:
a=pd.Series(['a','b','c',11])
a

0     a
1     b
2     c
3    11
dtype: object

In [45]:
a=pd.date_range(start='2-6-2000', end = '6-6-2019')
a

DatetimeIndex(['2000-02-06', '2000-02-07', '2000-02-08', '2000-02-09',
               '2000-02-10', '2000-02-11', '2000-02-12', '2000-02-13',
               '2000-02-14', '2000-02-15',
               ...
               '2019-05-28', '2019-05-29', '2019-05-30', '2019-05-31',
               '2019-06-01', '2019-06-02', '2019-06-03', '2019-06-04',
               '2019-06-05', '2019-06-06'],
              dtype='datetime64[ns]', length=7061, freq='D')

# Pandas DataFrame

- Dataframe is just like a table.which is going to contain rows and column 
- Row can have a index
- Column can have a meaning full names


In [49]:

import numpy as np
temp=np.random.randint(low=20,high=100,size=[20])
name=np.random.choice(['jaanu','jaan','janvi','jahnvi'],20)
av=np.random.choice([10,12,13,14,50],20)
a=list(zip(temp,name,av))
df=pd.DataFrame(data=a,columns=['temp','name','av'])
df


temp    name  av
0     73   jaanu  12
1     63   jaanu  13
2     62  jahnvi  14
3     22    jaan  50
4     95   janvi  10
5     25   janvi  10
6     65  jahnvi  10
7     50   janvi  12
8     30  jahnvi  12
9     38    jaan  12
10    69    jaan  50
11    81  jahnvi  12
12    63  jahnvi  14
13    32   jaanu  10
14    21    jaan  12
15    36    jaan  50
16    90  jahnvi  50
17    54   janvi  12
18    90   janvi  10
19    44   jaanu  50

In [48]:
import numpy as np


In [50]:
type(df)

pandas.core.frame.DataFrame

In [51]:
df.tail()

temp    name  av
15    36    jaan  50
16    90  jahnvi  50
17    54   janvi  12
18    90   janvi  10
19    44   jaanu  50

In [52]:
df.shape

(20, 3)

In [53]:
df.columns

Index(['temp', 'name', 'av'], dtype='object')

In [54]:
df.name

0      jaanu
1      jaanu
2     jahnvi
3       jaan
4      janvi
5      janvi
6     jahnvi
7      janvi
8     jahnvi
9       jaan
10      jaan
11    jahnvi
12    jahnvi
13     jaanu
14      jaan
15      jaan
16    jahnvi
17     janvi
18     janvi
19     jaanu
Name: name, dtype: object

In [55]:
df['name']

0      jaanu
1      jaanu
2     jahnvi
3       jaan
4      janvi
5      janvi
6     jahnvi
7      janvi
8     jahnvi
9       jaan
10      jaan
11    jahnvi
12    jahnvi
13     jaanu
14      jaan
15      jaan
16    jahnvi
17     janvi
18     janvi
19     jaanu
Name: name, dtype: object

In [56]:
df['temp'].describe()

count    20.000000
mean     55.150000
std      23.640454
min      21.000000
25%      35.000000
50%      58.000000
75%      70.000000
max      95.000000
Name: temp, dtype: float64

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
temp    20 non-null int64
name    20 non-null object
av      20 non-null int64
dtypes: int64(2), object(1)
memory usage: 560.0+ bytes


In [58]:
df.values

array([[73, 'jaanu', 12],
       [63, 'jaanu', 13],
       [62, 'jahnvi', 14],
       [22, 'jaan', 50],
       [95, 'janvi', 10],
       [25, 'janvi', 10],
       [65, 'jahnvi', 10],
       [50, 'janvi', 12],
       [30, 'jahnvi', 12],
       [38, 'jaan', 12],
       [69, 'jaan', 50],
       [81, 'jahnvi', 12],
       [63, 'jahnvi', 14],
       [32, 'jaanu', 10],
       [21, 'jaan', 12],
       [36, 'jaan', 50],
       [90, 'jahnvi', 50],
       [54, 'janvi', 12],
       [90, 'janvi', 10],
       [44, 'jaanu', 50]], dtype=object)

In [59]:
import numpy as np
aliet=np.random.randint(low=20,high=100,size=[20])
name=np.random.choice(['loyola','tech','andhra','btech'],2,)
av=np.random.choice([10,12,13,14,50],2)
a=list(zip(aliet,name,av))
df=pd.DataFrame(data=a,columns=['aliet','name','av'])
df


aliet  name  av
0     89  tech  10
1     39  tech  10